# Generated by Django 5.2.1 on 2025-05-20 04:22

import Api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente', models.CharField(default=Api.models.generar_id_paciente, editable=False, max_length=10, unique=True)),
                ('nombre_madre', models.CharField(max_length=150, verbose_name='Nombre de la madre')),
                ('documento_madre', models.CharField(max_length=20, verbose_name='Documento de la madre')),
                ('sexo_bebe', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo del bebé')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Talla (cm)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('hora_nacimiento', models.TimeField(verbose_name='Hora de nacimiento')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de registro')),
                ('dado_alta', models.CharField(choices=[('True', 'Sí'), ('False', 'No')], default='False', max_length=5, verbose_name='¿Dado de alta?')),
                ('codigo_qr', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código QR')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('Doctor(a)', 'Doctor(a)'), ('Enfermero(a)', 'Enfermero(a)')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
