# Generated by Django 5.2.1 on 2025-05-20 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('busqueda', 'Búsqueda'), ('creacion', 'Creación'), ('edicion', 'Edición')], max_length=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('metodo_busqueda', models.CharField(blank=True, choices=[('qr', 'Código QR'), ('id', 'ID de Paciente')], max_length=10, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='Api.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
