# Generated by Django 5.2.1 on 2025-05-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_actividadusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadusuario',
            name='detalles_cambio',
            field=models.JSONField(blank=True, null=True, verbose_name='Detalles del cambio'),
        ),
    ]
